server {
  listen 8080;
  server_name _;

  location = /proxy-health {
    default_type text/plain;
    return 200 "ok\n";
  }

  location /environment/ {
    proxy_pass http://aas-environment:8081/;
    proxy_set_header Authorization $http_authorization;
    proxy_set_header Host $host;
  }

  location /aas-registry/ {
    proxy_pass http://aas-registry:8080/;
    proxy_set_header Authorization $http_authorization;
    proxy_set_header Host $host;
  }

  location /submodel-registry/ {
    proxy_pass http://sm-registry:8080/;
    proxy_set_header Authorization $http_authorization;
    proxy_set_header Host $host;
  }

  location /discovery/ {
    proxy_pass http://aas-discovery:8081/;
    proxy_set_header Authorization $http_authorization;
    proxy_set_header Host $host;
  }
}

