server.port=8081
spring.application.name=Partner AAS Discovery Service
basyx.aasdiscoveryservice.name=partner-aas-discovery-service

basyx.backend=MongoDB
spring.data.mongodb.host=partner-mongo
spring.data.mongodb.database=partner-aas-discovery
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.username=${MONGO_ROOT_USERNAME}
spring.data.mongodb.password=${MONGO_ROOT_PASSWORD}

basyx.cors.allowed-origins=http://localhost:3100
basyx.cors.allowed-methods=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD

