server.port=8081

basyx.backend=MongoDB
spring.data.mongodb.host=partner-mongo
spring.data.mongodb.database=partner-aas-environment
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.username=${MONGO_ROOT_USERNAME}
spring.data.mongodb.password=${MONGO_ROOT_PASSWORD}

basyx.environment=file:aas
basyx.aasrepository.feature.registryintegration=http://partner-aas-registry:8080
basyx.aasrepository.feature.discoveryintegration=http://partner-aas-discovery:8081
basyx.submodelrepository.feature.registryintegration=http://partner-sm-registry:8080
basyx.externalurl=http://localhost:8181

basyx.cors.allowed-origins=http://localhost:3100
basyx.cors.allowed-methods=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
spring.servlet.multipart.max-request-size=128MB
spring.servlet.multipart.max-file-size=128MB

